<a href="https://colab.research.google.com/github/RihaChri/ImageClassificationBreastCancer/blob/main/Bewerbungstests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Umgekehrte Ganze Zahl
Erstellen Sie eine Funktion, die eine ganze Zahl rückwärts geschrieben wieder ausgibt.


In [2]:

def reverseInteger(x):
    string = str(x)
    
    if string[0] == '-':
        return int('-'+string[:0:-1])
    else:
        return int(string[::-1])
print(reverseInteger(-231))
print(reverseInteger(345))

-132
543


# Durchschnittliche Wortlänge
Erstellen Sie eine Funktion, die die durchschnittliche Wortlänge eines Satzes berechnet.

In [4]:
def avWordLen(x):
    
    for i in '.,!?&%$ยง-_:;<>|':
        x=x.replace(i,"")
    print('Sentence without special character:'+x)
    r=x.split(" ")
    sum=0
    for i in r:
        sum+=len(i)
    average=sum/len(r)
    return average
print(avWordLen("Hallo ich mag Krokodile...,!?&%$ยง-_:;<>|.."))

Sentence without special character:Hallo ich mag Krokodile
5.0


# Summen berechnen
Schreiben Sie eine Funktion, die Summen berechnet.

In [5]:
print('sum up values')
num1 = '364'
num2 = '1836'

# Approach 1: 
def sumWithEval(num1,num2):
    return str(eval(num1) + eval(num2))
            
print(sumWithEval(num1,num2))

sum up values
2200


# Einzigartiger Buchstabe
Schreibe einen Funktion, die den Indes des ersten einzigartigen Buchstaben eines String zurückgibt

In [8]:
print('first Unique Character')
def FirstUniqueCharacter(s):
    frequency = {}
    for i in s:
        if i not in frequency:
            frequency[i] = 1
        else:
            frequency[i] +=1
    for i in range(len(s)):
        if frequency[s[i]] == 1:
            return i
    return -1

print(FirstUniqueCharacter('alphabet'))
print(FirstUniqueCharacter('barbados'))
print(FirstUniqueCharacter('crunchy'))

first Unique Character
1
2
1


# Einzigartiger Buchstabe, alternative
Schreibe wieder eine Funktion, die den Index des ersten einzigartigen Buchstaben ausgibt.

In [10]:
import collections
def FirstUniqueCharacterVariantB(s):
    # build hash map : character and how often it appears
    count = collections.Counter(s) # <-- gives back a dictionary with words occurrence count 
                                            #Counter({'l': 1, 'e': 3, 't': 1, 'c': 1, 'o': 1, 'd': 1})
    
    # find the index
    for idx, ch in enumerate(s):
        if count[ch] == 1:
            return idx     
    return -1

print(FirstUniqueCharacterVariantB('alphabet'))
print(FirstUniqueCharacterVariantB('barbados'))
print(FirstUniqueCharacterVariantB('crunchy'))

1
2
1


# Palendrome
Schreibe eine Funktion, die angibt, ob der String ein Palendrom ist

In [12]:
s = 'Kroko'
def Palendrome(s):
    for i in range(len(s)):
        t = s[:i] + s[i+1:]
        print(t)
        if t == t[::-1]: return True

    return s == s[::-1]
  
print(Palendrome(s))


roko
Koko
Krko
Kroo
Krok
False
monotonic?


# Monoton
Schreiben Sie eine Funktion, die auswertet, ob eine Zahlreihe monoton steigend ist

In [13]:
A = [6, 5, 4, 4] 
B = [1,1,1,3,3,4,3,2,4,2]
C = [1,1,2,3,7]


def monotonic(nums): 
    return (all(nums[i] <= nums[i + 1] for i in range(len(nums) - 1)) or 
            all(nums[i] >= nums[i + 1] for i in range(len(nums) - 1))) 
  
print(monotonic(A)) 
print(monotonic(B)) 
print(monotonic(C)) 

print('Zeroes at the end')
array1 = [0,1,0,3,12]
array2 = [1,7,0,0,8,0,10,12,0,4]

True
False
True
Zeroes at the end


# Nullen sortieren
Schreibe eine Funktion, die die Nullen einer Zahl ans Ende der Zahl schreibt.

In [15]:
print('Zeroes at the end')
array1 = [0,1,0,3,12]
array2 = [1,7,0,0,8,0,10,12,0,4]

def solution(nums):
    lens=len(nums)
    print(lens)
    for i in range(lens):
        if 0 in nums:
            print(nums)
            nums.remove(0)
            nums.append(0)
            print(nums)
    return nums

print(solution(array1))
print(solution(array2))


Zeroes at the end
5
[0, 1, 0, 3, 12]
[1, 0, 3, 12, 0]
[1, 0, 3, 12, 0]
[1, 3, 12, 0, 0]
[1, 3, 12, 0, 0]
[1, 3, 12, 0, 0]
[1, 3, 12, 0, 0]
[1, 3, 12, 0, 0]
[1, 3, 12, 0, 0]
[1, 3, 12, 0, 0]
[1, 3, 12, 0, 0]
10
[1, 7, 0, 0, 8, 0, 10, 12, 0, 4]
[1, 7, 0, 8, 0, 10, 12, 0, 4, 0]
[1, 7, 0, 8, 0, 10, 12, 0, 4, 0]
[1, 7, 8, 0, 10, 12, 0, 4, 0, 0]
[1, 7, 8, 0, 10, 12, 0, 4, 0, 0]
[1, 7, 8, 10, 12, 0, 4, 0, 0, 0]
[1, 7, 8, 10, 12, 0, 4, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]
[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]


# Ersetzen
Schreiben Sie eine Funktion, die alle None mit der jeweils letzten Zahl ersetzt.

In [16]:
array1 = [1,None,2,3,None,None,5,None]

def solution(array):
    valid = 0            
    res = []                 
    for i in array: 
        if i is not None:    
            res.append(i)
            valid = i
        else:
            res.append(valid)
    return res

print(solution(array1))

[1, 1, 2, 3, 3, 3, 5, 5]


# Gleiche Wortei in zwei Sätzen
Schreiben Sie eine Funktion, die in zwei Sätzen gleiche Worte herausfindet.

In [17]:
sentence1 = 'We are really pleased to meet you in our city'
sentence2 = 'The city was hit by a really heavy storm'

def solution(sentence1, sentence2):
    set1 = set(sentence1.split())
    print(sentence1.split())
    print(set1)
    set2 = set(sentence2.split())
    print(sentence2.split())
    print(set2)
    
    print(list(set1^set2))
    print(list(set1&set2))
    
    return sorted(list(set1^set2)), sorted(list(set1&set2)) # ^ A.symmetric_difference(B), & A.intersection(B)

print(solution(sentence1, sentence2))

['We', 'are', 'really', 'pleased', 'to', 'meet', 'you', 'in', 'our', 'city']
{'are', 'We', 'to', 'in', 'really', 'our', 'pleased', 'meet', 'city', 'you'}
['The', 'city', 'was', 'hit', 'by', 'a', 'really', 'heavy', 'storm']
{'a', 'really', 'by', 'heavy', 'The', 'storm', 'hit', 'city', 'was'}
['are', 'We', 'a', 'to', 'meet', 'you', 'by', 'heavy', 'The', 'our', 'pleased', 'storm', 'hit', 'was', 'in']
['really', 'city']
(['The', 'We', 'a', 'are', 'by', 'heavy', 'hit', 'in', 'meet', 'our', 'pleased', 'storm', 'to', 'was', 'you'], ['city', 'really'])


# Primzahl
Schreiben Sie eine Funktion, die herausfindet, welche natürlichen Zahlen sie kkleiner als eine angegebene Zahl sind, Primzahlen sind.

In [18]:
n = 35
def primenum(n):
    prime_nums = []
    for num in range(2,n):
            for i in range(2, num):
                if (num % i) == 0: # if the modulus == 0 is means that the number can be divided by a number preceding it
                    break
            else:
                prime_nums.append(num)
    return prime_nums
print(primenum(n))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]


# Starke Zahl
Schreiben Sie eine Funktion, die herausfindet, ob eine Zahl eine Starke Zahl ist. Eine Starke Zahl ist z.B. 125, denn 1! + 2! + 5!= 1 + 4 + 120 = 125.

In [22]:
def strongNumber(x):
    x=str(x)
    prod=1
    sum=0
    for idx, elem in enumerate(x):
        for j in range(1,int(elem)+1):
            prod*=j
        sum+=prod
        prod=1
        
    return sum==int(x)
print(strongNumber(145))


True


# Zweit größte Zahl
Schreiben sie eine funktion, die die zweit größte Zahl einer Liste ausgibt

In [23]:
nList=[3, 4, 1, 2, 6]
nList.sort()
print(nList[-2])

4


# Perfekte Zahl
Wenn alle natürlichen Zahlen, die kleiner als die angegebene Zahl sind, durch die sich die angegebene Zahl teilen lässt, zusammenmultipliziert werden können und die angegebene Zahl ergeben.

In [25]:
def perfectNumber(x):
    dList = []
    dSum=0
    for i in range(1,x):
        if x%i==0:
            dList.append(i)
            dSum+=i
    print(dList)
    
    return dSum==x
print(perfectNumber(6))

[1, 2, 3]
True


#Narzistische Funktion
Das ist zu krank das zu erklären... 4^3+0^3+7^3=407... tada eine narzistische Funktion.

In [26]:
def narziss(x):
    x=str(x)
    xSum=0
    for elem in x:
        xSum+=int(elem)**len(x)
    return(xSum==int(x))

print(narziss(407))

print(456-456%100)

True
400


# Klassen

In [27]:
class Kroko:
    def __init__ (self, name, element, sin="noSin"):
        self.name = name
        self.element = element
        self.sin = sin
        
        self.firstName = self.name.split()[0]
        self.lastName = self.name.split()[1]
        
    def attack(self):
        print(self.sin+" attack!")

        
Hadegen=Kroko("Hadegen Senftenberg", "Leben")  
print(Hadegen.name)
print(Hadegen.lastName)
Hadegen.attack()

Hadegen Senftenberg
Senftenberg
noSin attack!


#Länder

In [28]:
countries = ("Germany", "Pakistan", "China", "Turkey", "Australia", "France")

print(countries[0:5:2])

('Germany', 'China', 'Australia')


# Quadratische Funktionen mit lamnda expression

In [29]:
def quadratischeFunktion(a,b,c):
    return lambda x:x**2*a+x*b+c

a=quadratischeFunktion(1,1,1)
print(a(1))

3


# Liste mit lambda

In [30]:
listeKroko = ['Naxi Feuer', 'Brudi Erde', 'Normen de Gun Wind', 'Nitz Garcia Wasser', 'Rayo di Sol Ordnung']
listeKroko.sort(key=lambda name: name.split()[-1])
print(listeKroko)

['Brudi Erde', 'Naxi Feuer', 'Rayo di Sol Ordnung', 'Nitz Garcia Wasser', 'Normen de Gun Wind']


# Lambda

In [31]:
x = lambda a: a * 14
print(x(3))

42


# Vargs Beispiel

In [32]:
def Kro1(*argv):
    for i in argv:
        print(i)

Kro1('Crocodile', 'Alligator', 'Gavial')

def Kro2(**kwargs):
    for i,j in kwargs.items():
        print(str(i)+" "+str(j))

KroDic=dict(Naxi="Feuer",
        Brudi="Erde",
        Normen="Luft",
        Nitz="Wasser")

Kro2(**KroDic)

Crocodile
Alligator
Gavial
Naxi Feuer
Brudi Erde
Normen Luft
Nitz Wasser


# Arrays

In [33]:
print('add arrays')
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.sum((a,b),axis=0))

add arrays
[5 7 9]


#Imort iris dataset

In [ ]:
import pandas as pd

iris = pd.read_csv('iris.csv')

df = pd.DataFrame(iris) 

a=df.loc[:,'sepal.length']
b=df.loc[:,'sepal.width']
idxList=[]
for i in range(len(a)):
    if a[i]>6 and b[i]>3.3:
        idxList.append(i)
print("ergebnis")  
print(idxList)


print('ListenTest:')
a=[i for i in range(10)]
print(a)
b=[i for i in a if i>5 and i<9]
print(b)

#Lists

In [34]:
import numpy as np
#You can change entries of a list
mylist = [1, "banana", "cherry"]
mylist.append("blueberry")
print(mylist)
mylist[-1]="notBlueberry"
print(mylist)
print(mylist[-1])
#----------------------------------
mytuple = (1, "banana", "cherry")
print(mytuple)
print(mytuple[-1])
#----------------------------------
myArray=np.array([1, "banana", "cherry"])
myArray2=np.array([1, 2, 3])
print(myArray)
print(myArray2)
print(myArray[-1])
#------------------------------------
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

thisdict["neuerEintrag"]="neuneu"
print(thisdict["brand"])
print(thisdict["neuerEintrag"])
#-------------------------------
kString="Kroko"
print(kString)
kList=list(kString)
print(kList)
kList[2]="u"
print(kList)
modString=''.join(kList)
print(modString)
#------------converting-----------------
tupli=(1,2)
print(tupli)
print(str(tupli)[:])
print(list(tupli))

Listi=[1, 2, 3, 4]
setListi=set(Listi)
print(Listi)
print(setListi)
print(next(iter(setListi)))
listiagain=list(setListi)
print(listiagain)




[1, 'banana', 'cherry', 'blueberry']
[1, 'banana', 'cherry', 'notBlueberry']
notBlueberry
(1, 'banana', 'cherry')
cherry
['1' 'banana' 'cherry']
[1 2 3]
cherry
Ford
neuneu
Kroko
['K', 'r', 'o', 'k', 'o']
['K', 'r', 'u', 'k', 'o']
Kruko
(1, 2)
(1, 2)
[1, 2]
[1, 2, 3, 4]
{1, 2, 3, 4}
1
[1, 2, 3, 4]


#Numpy

In [35]:
import numpy as np
np.random.seed(0)
a = np.random.randint(1, 10, size=(5,2))
print(a)
print(a.shape)
b = np.array([[6, 1],[4, 4],[8, 4],[6, 3],[5, 8]])
print(b)
print(b.shape)
c = np.array([[6, 1, 1],[4, 4, 1]])
print(c)
print(c.shape)

#print(a+b)
#print(a-b)
#print(a*2)
#print(a+2)
print("multipli:"+str(np.dot(a,c).shape))



vector1=np.array([[6, 1, 3, 4, 6]])
vector2=vector1.T
print(vector1.shape)
print(vector2.shape)
print(np.dot(vector1,vector2).shape)
print(np.dot(vector2,vector1).shape)

[[6 1]
 [4 4]
 [8 4]
 [6 3]
 [5 8]]
(5, 2)
[[6 1]
 [4 4]
 [8 4]
 [6 3]
 [5 8]]
(5, 2)
[[6 1 1]
 [4 4 1]]
(2, 3)
multipli:(5, 3)
(1, 5)
(5, 1)
(1, 1)
(5, 5)


#Yield

In [36]:
class Parent:
    temper=32
    def __init__(self):
        self.age=32
        
        
class Child(Parent):
    pass
        
        
a=Parent()
print("Parent age: "+str(a.age))
print("Parent temper: "+str(a.temper))
b=Child()

print("Child age: "+str(b.age))
print("Child temper: "+str(b.temper))
a.age=33
a.temper=33
print("Parent age: "+str(a.age))
print("Parent temper: "+str(a.temper))
print("Child age: "+str(b.age))
print("Child temper: "+str(b.temper))


print(Parent.temper)
    

def fun1():
    for i in range(1,10):
        yield i
   
def fun2(elem):
    for i in elem:
        yield i*2
        
obj=fun2(fun1())
print(next(obj))
print(next(obj))


Parent age: 32
Parent temper: 32
Child age: 32
Child temper: 32
Parent age: 33
Parent temper: 33
Child age: 32
Child temper: 32
32
2
4
